/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.quanlykhachsan.view;

import java.sql.SQLException;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import com.quanlykhachsan.dao.ChiTietHoaDon_DAO;
import com.quanlykhachsan.dao.DichVu_DAO;
import com.quanlykhachsan.dao.HoaDon_DAO;
import com.quanlykhachsan.dao.KhachHang_DAO;
import com.quanlykhachsan.dao.LichSuDatDichVu_DAO;
import com.quanlykhachsan.dao.LichSuDatPhong_DAO;
import com.quanlykhachsan.dao.LoaiPhong_DAO;
import com.quanlykhachsan.dao.NhanVien_DAO;
import com.quanlykhachsan.dao.Phong_DAO;
import com.quanlykhachsan.entity.ChiTietHoaDon;
import com.quanlykhachsan.entity.DichVu;
import com.quanlykhachsan.entity.HoaDon;
import com.quanlykhachsan.entity.KhachHang;
import com.quanlykhachsan.entity.LichSuDatDichVu;
import com.quanlykhachsan.entity.LichSuDatPhong;

import com.quanlykhachsan.entity.NhanVien;
import com.quanlykhachsan.entity.Phong;

import com.quanlykhachsan.enum_Class.TrangThaiHoaDon;
import com.quanlykhachsan.enum_Class.TrangThaiPhong;
import com.quanlykhachsan.enum_Class.TrangThaiTaiKhoan;
import com.quanlykhachsan.entity.LoaiPhong;
import com.quanlykhachsan.entity.Voucher;

/**
 *
 * @author liemh
 */
public class ThongTinDatPhong extends javax.swing.JPanel {

	/**
	 * Creates new form ThongTinDatPhong
	 */
	private final double coc = 0.2;
	private KhachHang_DAO kh_dao;
	private DichVu_DAO dv_dao;
	private LoaiPhong_DAO lp_dao;
	private ChiTietHoaDon_DAO cthd_dao;
	private LichSuDatDichVu_DAO lsddv_dao;
	private LichSuDatPhong_DAO lsdp_dao;
	private HoaDon_DAO hd_dao;
	private NhanVien_DAO nv_dao;
	private Phong_DAO p_dao;
	private DefaultTableModel modelDichVu = new DefaultTableModel(new String [] {
            "Mã Dịch vụ", "Tên Dịch Vụ", "Số Lượng", "Thành Tiền"
        }, 0);
	private Phong phong;
	private JFrame parentFrame;
	public Phong getPhong() {
		return phong;
	}

	public void setPhong(Phong phong) {
		this.phong = phong;
	}

	public ThongTinDatPhong(Phong phong, JFrame parentFrame) {
		this.phong = phong;
		this.parentFrame = parentFrame;
		initComponents();
		p_dao = new Phong_DAO();
		kh_dao = new KhachHang_DAO();
		dv_dao = new DichVu_DAO();
		lp_dao = new LoaiPhong_DAO();
		cthd_dao = new ChiTietHoaDon_DAO();
		lsddv_dao = new LichSuDatDichVu_DAO();
		lsdp_dao = new LichSuDatPhong_DAO();
		hd_dao = new HoaDon_DAO();
		nv_dao = new NhanVien_DAO();
		loadComboxDichVu();
		
		jTextFieldTongTien.setText(Double.toString(tinhTongTien()));
		nv_dao.timNhanVienTheoTrangThaiTaiKhoan(TrangThaiTaiKhoan.DANG_HOAT_DONG);
    	List<NhanVien> dsnv = nv_dao.getList();
		jTextFieldTenNhanVien.setText(dsnv.get(0).getTenNhanVien());
		jDateChooserCheckIn.setDate(java.sql.Date.valueOf(LocalDate.now()));
		jSpinFieldThoiGianDat.setValue(1);
		jDateChooserCheckOut.setDate(java.sql.Date.valueOf(LocalDate.now().plusDays(1)));

	}
	
	private double tinhTongTien() {
		lp_dao.docTuBang();
		LoaiPhong lp = lp_dao.timTheoMa(phong.getLoaiPhong().getMaLoaiPhong());
		double giaThuePhong = jSpinFieldThoiGianDat.getValue() * lp.getGiaThuePhong();
		double tongtienDichVu = 0;
		for (int i = 0; i < modelDichVu.getRowCount(); i++) {
			tongtienDichVu += Double.parseDouble(modelDichVu.getValueAt(i, 3).toString());
		}
		return giaThuePhong + tongtienDichVu;

	}

	private void loadComboxDichVu() {
			jComboBoxDichVu.removeAllItems();

            ArrayList<DichVu> dsdv = new ArrayList<DichVu>();
            dsdv = dv_dao.getDsDichVu();
            dsdv.stream().forEach(x->{
            	jComboBoxDichVu.addItem(x.getTenDichVu());
            });
        }
		
	

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        labelPhong = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        labelGia = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        labelLoaiPhong = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        labelNhanVien = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtTenKH = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtSDT = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtCCCD = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        comBoBoxDV = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        spinnerSL = new javax.swing.JSpinner();
        jLabel21 = new javax.swing.JLabel();
        txtGia = new javax.swing.JTextField();
        btnThemDV = new javax.swing.JButton();
        btnXoaDV = new javax.swing.JButton();
        btnXoaToanBoDV = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableDV = new javax.swing.JTable();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablePhong = new javax.swing.JTable();
        jPanel14 = new javax.swing.JPanel();
        btnDatPhong = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtTenKHCT = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        btnThemKH = new javax.swing.JButton();
        btnXoaKH = new javax.swing.JButton();
        btnXoaKHToanBo = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        radioTreEm = new javax.swing.JRadioButton();
        radioNguoiLon = new javax.swing.JRadioButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableKH = new javax.swing.JTable();
        jLabel22 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1920, 1080));

        jPanel1.setPreferredSize(new java.awt.Dimension(1920, 1080));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("Thông tin phòng");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setText("Phòng");

        labelPhong.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        labelPhong.setText("XXXXXXXXX");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setText("Loại phòng");

        labelGia.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        labelGia.setText("XXXXXXXXX");

        jLabel14.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel14.setText("Giá");

        labelLoaiPhong.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        labelLoaiPhong.setText("XXXXXXXXX");

        jLabel10.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel10.setText("Nhân viên");

        labelNhanVien.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        labelNhanVien.setText("XXXXXXXXX");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("Khách hàng đại diện");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setText("Tên khách hàng");

        txtTenKH.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtTenKH.setEnabled(false);

        jLabel9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel9.setText("Số điện thoại");

        txtSDT.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jLabel19.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel19.setText("CCCD");

        txtCCCD.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel9)
                            .addComponent(jLabel19))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSDT, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                            .addComponent(txtTenKH)
                            .addComponent(txtCCCD)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel3)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtCCCD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jLabel12.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel12.setText("Dịch vụ");

        jLabel13.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel13.setText("Số lượng");

        comBoBoxDV.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        comBoBoxDV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comBoBoxDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comBoBoxDVActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel15.setText("Dịch vụ");

        spinnerSL.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jLabel21.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel21.setText("Giá");

        txtGia.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtGia.setEnabled(false);
        txtGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGiaActionPerformed(evt);
            }
        });

        btnThemDV.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnThemDV.setText("Thêm");

        btnXoaDV.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnXoaDV.setText("Xóa");
        btnXoaDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaDVActionPerformed(evt);
            }
        });

        btnXoaToanBoDV.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnXoaToanBoDV.setText("Xóa toàn bộ");

        tableDV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Tên dịch vụ", "Giá ", "Số lượng"
            }
        ));
        jScrollPane2.setViewportView(tableDV);
        if (tableDV.getColumnModel().getColumnCount() > 0) {
            tableDV.getColumnModel().getColumn(2).setResizable(false);
        }

        tablePhong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã phòng", "Lọai phòng", "Giá"
            }
        ));
        jScrollPane4.setViewportView(tablePhong);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        btnDatPhong.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnDatPhong.setText("Xác nhận");

        btnHuy.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnHuy.setText("Hủy");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(btnDatPhong)
                .addGap(59, 59, 59)
                .addComponent(btnHuy)
                .addContainerGap(160, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDatPhong)
                    .addComponent(btnHuy))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel21)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel12))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(btnThemDV)
                        .addGap(38, 38, 38)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(btnXoaDV)
                                .addGap(18, 18, 18)
                                .addComponent(btnXoaToanBoDV))
                            .addComponent(spinnerSL, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comBoBoxDV, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(42, 42, 42)
                    .addComponent(jLabel15)
                    .addContainerGap(285, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel13)
                        .addGap(69, 69, 69)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnThemDV)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnXoaDV)
                                .addComponent(btnXoaToanBoDV)))
                        .addGap(123, 123, 123)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(comBoBoxDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(spinnerSL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(53, 53, 53)
                    .addComponent(jLabel15)
                    .addContainerGap(166, Short.MAX_VALUE)))
        );

        jLabel16.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel16.setText("Thông tin khách hàng");

        jLabel18.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel18.setText("Tên khách hàng");

        txtTenKHCT.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jLabel20.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel20.setText("Loại người");

        btnThemKH.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnThemKH.setText("Thêm");

        btnXoaKH.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnXoaKH.setText("Xóa");

        btnXoaKHToanBo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnXoaKHToanBo.setText("Xóa toàn bộ");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 493, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 348, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(btnThemKH)
                .addGap(38, 38, 38)
                .addComponent(btnXoaKH)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnXoaKHToanBo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemKH)
                    .addComponent(btnXoaKH)
                    .addComponent(btnXoaKHToanBo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );

        radioTreEm.setText("Trẻ em");

        radioNguoiLon.setText("Người lớn");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(39, 39, 39)
                        .addComponent(txtTenKHCT, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(34, 34, 34)
                        .addComponent(radioTreEm)
                        .addGap(18, 18, 18)
                        .addComponent(radioNguoiLon)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel16)
                .addGap(139, 139, 139))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtTenKHCT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(radioTreEm)
                    .addComponent(radioNguoiLon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        tableKH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Tên khách hàng", "Loại người"
            }
        ));
        jScrollPane3.setViewportView(tableKH);

        jLabel22.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel22.setText("Danh sách phòng");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(37, 37, 37)
                .addComponent(labelNhanVien)
                .addGap(691, 691, 691))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel4)
                        .addGap(74, 74, 74)
                        .addComponent(labelPhong)
                        .addGap(90, 90, 90)
                        .addComponent(jLabel7))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addGap(57, 57, 57)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(labelLoaiPhong)
                        .addGap(75, 75, 75)
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(labelGia)
                        .addGap(151, 151, 151)
                        .addComponent(jLabel22)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 650, Short.MAX_VALUE))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel10)
                    .addComponent(labelNhanVien))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(labelPhong)
                            .addComponent(jLabel7)
                            .addComponent(labelLoaiPhong)
                            .addComponent(jLabel14)
                            .addComponent(labelGia))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel22)))
                .addContainerGap(535, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(560, 560, 560))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(687, 687, 687))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void comBoBoxDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comBoBoxDVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comBoBoxDVActionPerformed

    private void txtGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGiaActionPerformed

    private void btnXoaDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaDVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXoaDVActionPerformed

	private void jRadioButtonDatStateChanged(javax.swing.event.ChangeEvent evt) {                                             
		 if (jRadioButtonDat.isSelected()) {
		        jDateChooserCheckIn.setEnabled(false);
		    	jDateChooserCheckOut.setEnabled(false);// Làm mờ, không cho phép chọn
		    	jTextFieldTienCoc.setText("");
		    } else {
		        jDateChooserCheckOut.setEnabled(false);  // Kích hoạt lại nếu bỏ chọn
		    }
	}


    private void jRadioButtonDatTruocStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRadioButtonDatTruocStateChanged
    	if (jRadioButtonDatTruoc.isSelected()) {
    		jDateChooserCheckIn.setEnabled(true);
	        jDateChooserCheckOut.setEnabled(false); // Làm mờ, không cho phép chọn
	        lp_dao.docTuBang();
			LoaiPhong lp = lp_dao.timTheoMa(phong.getLoaiPhong().getMaLoaiPhong());
	        jTextFieldTienCoc.setText(String.valueOf(lp.getGiaThuePhong()*coc));
	    } else {
	        jDateChooserCheckOut.setEnabled(false);
	        jDateChooserCheckIn.setEnabled(false);// Kích hoạt lại nếu bỏ chọn
	    }
    }//GEN-LAST:event_jRadioButtonDatTruocStateChanged

    private void jRadioButtonNgayStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRadioButtonNgayStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonNgayStateChanged

    private void jRadioButtonGioStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRadioButtonGioStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonGioStateChanged

    private void jComboBoxDichVuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxDichVuMouseClicked
    }//GEN-LAST:event_jComboBoxDichVuMouseClicked

    private void jSpinnerSoLuongDichVuStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerSoLuongDichVuStateChanged
    	 int i = jComboBoxDichVu.getSelectedIndex(); // Lấy chỉ mục đã chọn từ jComboBox
    	    ArrayList<DichVu> dsdv = dv_dao.getDsDichVu(); // Lấy danh sách dịch vụ từ dv_dao

    	    // Kiểm tra nếu chỉ mục hợp lệ
    	    if (i >= 0 && i < dsdv.size()) {
    	        // Lấy số lượng từ jSpinner
    	        int soLuong = (int) jSpinnerSoLuongDichVu.getValue();

    	        // Tính tiền dựa trên số lượng và giá dịch vụ
    	        double tien = soLuong * dsdv.get(i).getGiaDichVu();

    	        // Hiển thị tổng tiền trong jTextFieldGiaDichVu
    	        jTextFieldGiaDichVu.setText(String.valueOf(tien));
    	    }
    	    
    }//GEN-LAST:event_jSpinnerSoLuongDichVuStateChanged

    private void jSpinFieldThoiGianDatPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jSpinFieldThoiGianDatPropertyChange
		LocalDate checkInDate = jDateChooserCheckIn.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
		int soNgay = jSpinFieldThoiGianDat.getValue();
		LocalDate checkOutDate = checkInDate.plusDays(soNgay);
		jDateChooserCheckOut.setDate(java.sql.Date.valueOf(checkOutDate));
		jTextFieldTongTien.setText(Double.toString(tinhTongTien()));
    }//GEN-LAST:event_jSpinFieldThoiGianDatPropertyChange

    private void jComboBoxDichVuPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jComboBoxDichVuPropertyChange
    }//GEN-LAST:event_jComboBoxDichVuPropertyChange

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        jTextFieldTenKhachHang.setText("");
        jTextFieldSoDienThoai.setText("");
        jSpinFieldThoiGianDat.setValue(1);
        jRadioButtonDat.setSelected(true);
        jRadioButtonNgay.setSelected(true);
        jComboBoxDichVu.setSelectedIndex(0);
        jSpinnerSoLuongDichVu.setValue(0);
        jTextFieldGiaDichVu.setText("");
        jTextFieldTienCoc.setText("");
        jTextFieldTongTien.setText("");
        for (int i = modelDichVu.getRowCount() - 1; i >= 0; i--) {
            modelDichVu.removeRow(i);
        }
        jTextFieldTongTien.setText( Double.toString(tinhTongTien()));

    }//GEN-LAST:event_jButtonResetActionPerformed

private void jButtonXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonXacNhanActionPerformed
		LoaiPhong lp = lp_dao.timTheoMa(phong.getLoaiPhong().getMaLoaiPhong());
    	nv_dao.timNhanVienTheoTrangThaiTaiKhoan(TrangThaiTaiKhoan.DANG_HOAT_DONG);
    	List<NhanVien> dsnv = nv_dao.getList();
    	NhanVien nv = dsnv.get(0);//nghiệp vụ chỉ có 1 nhân viên đang onl
    	Voucher voucher = null;
    	KhachHang kh = kh_dao.timKhachHangTheoSoDienThoai(jTextFieldSoDienThoai.getText());
    	double VAT = 0;
    	boolean tt = false;
    	LocalDate tgCheckiN;
    	
    	tgCheckiN = jDateChooserCheckIn.getDate().toInstant()
    	               .atZone(ZoneId.systemDefault())
    	               .toLocalDate();
    	int soNgayDat = jSpinFieldThoiGianDat.getValue();
    	double tienCoc = 0;
    	double tienPhat = 0;
    	double tongTien = Double.parseDouble(jTextFieldTongTien.getText());
    	LocalDate tgCheckOut = tgCheckiN.plusDays(soNgayDat);
    	if (jRadioButtonDat.isSelected()) { // Kiểm tra nếu radio button được chọn
    	    jTextFieldTienCoc.setText("");
    	    phong.setTrangThai(TrangThaiPhong.DA_DAT);
    	}else {
    		tienCoc = lp.getGiaThuePhong() * coc;
    		jTextFieldTienCoc.setText(String.valueOf(tienCoc));
    		phong.setTrangThai(TrangThaiPhong.DA_COC);
    		tt = true;
    	}
    	String maHoaDon = taoMaHoaDon();
    	HoaDon hd = new HoaDon(maHoaDon, LocalDate.now(), nv, voucher, kh
    			, VAT, tt, tgCheckiN, tgCheckOut, tienCoc, tienPhat, tongTien);
    	hd_dao.themHoaDon(hd);
    	String maCTHD = taoMaChiTietHoaDon();//
    	
    	ChiTietHoaDon cthd = new ChiTietHoaDon(maCTHD//1
                ,  
    			,LocalDate.now()
    			,lp.getGiaThuePhong()*soNgayDat
                , hd);
    	cthd_dao.themChiTietHoaDon(cthd);
    	LichSuDatPhong lsdp = new LichSuDatPhong(cthd, phong,1,LocalDate.now());//2
    	lsdp_dao.themLichSuDatPhong(lsdp);
    	int soLuongDichVU = modelDichVu.getRowCount();
    	for(int i = 0; i<soLuongDichVU;i++) {
    		DichVu dv = dv_dao.timDichVu(modelDichVu.getValueAt(i, 0).toString());
    		int soLuong = Integer.parseInt(modelDichVu.getValueAt(i, 2).toString());
    		String maCTHD_DV = taoMaChiTietHoaDon();//
        	ChiTietHoaDon cthd_dv = new ChiTietHoaDon(maCTHD_DV//1
                        ,  
        			,LocalDate.now()
        			,dv.getGiaDichVu()*soLuong
                    , hd);       	
        	cthd_dao.themChiTietHoaDon(cthd_dv);
    		LichSuDatDichVu lsdv = new LichSuDatDichVu(cthd_dv, dv, LocalDate.now(),soLuong);//3
    		lsddv_dao.themLichSuDatDichVu(lsdv);
    	}
    	
    	
    	
    	try {
			p_dao.capNhatPhong(phong);
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
    	if (parentFrame != null) {
            parentFrame.dispose(); // Đóng JFrame chứa JPanel này
        }
    }//GEN-LAST:event_jButtonXacNhanActionPerformed

    private void jDateChooserCheckInPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateChooserCheckInPropertyChange
		Date selectedDate = jDateChooserCheckIn.getDate();
		LocalDate checkInDate = selectedDate.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
		int soNgay = jSpinFieldThoiGianDat.getValue();
		LocalDate checkOutDate = checkInDate.plusDays(soNgay);
		jDateChooserCheckOut.setDate(java.sql.Date.valueOf(checkOutDate));
    }//GEN-LAST:event_jDateChooserCheckInPropertyChange

	private String taoMaHoaDon() {
		hd_dao.docTuBang();
		int i = hd_dao.getList().size();
		LocalDate ngayLapHoaDon = LocalDate.now();
	    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("ddMMyyyy");
	    String ngayFormatted = ngayLapHoaDon.format(formatter); // Định dạng ngày

	    // Tạo số tự động (YYY) với 3 chữ số
	    String soTuDong = String.format("%03d", i + 1); // i + 1 để bắt đầu từ 1

	    // Kết hợp thành mã chi tiết hóa đơn
	    return "HD" + ngayFormatted + "-" + soTuDong;
	}

	private String taoMaChiTietHoaDon() {
	    // Đọc dữ liệu từ bảng chi tiết hóa đơn
	    cthd_dao.docTuBang();
	    
	    // Lấy kích thước của danh sách hiện tại
	    int i = cthd_dao.getList().size(); // Giả sử i bắt đầu từ 0
	    
	    // Lấy ngày hiện tại và định dạng
	    LocalDate ngayLapHoaDon = LocalDate.now();
	    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("ddMMyyyy");
	    String ngayFormatted = ngayLapHoaDon.format(formatter); // Định dạng ngày

	    // Tạo số tự động (YYY) với 3 chữ số
	    String soTuDong = String.format("%03d", i + 1); // i + 1 để bắt đầu từ 1

	    return "CTHD1" + ngayFormatted + "-" + soTuDong;
	}

	private void jTextFieldSoDienThoaiFocusLost(java.awt.event.FocusEvent evt) {                                                 
	    String soDienThoai = jTextFieldSoDienThoai.getText(); // Lấy số điện thoại từ text field
	    KhachHang khachHang = kh_dao.timKhachHangTheoSoDienThoai(soDienThoai); // Gọi hàm tìm khách hàng theo số điện thoại
	    
	    if (khachHang != null) {
	        jTextFieldTenKhachHang.setText(khachHang.getTenKhachHang()); // Nếu tìm thấy, hiển thị tên khách hàng
	        // Bạn có thể đặt thêm các trường thông tin khác nếu cần, ví dụ:
	        // jTextFieldDiaChi.setText(khachHang.getDiaChi());
	    } else {
	        JOptionPane.showMessageDialog(this, "Không tìm thấy khách hàng với số điện thoại này.", "Thông báo",
	                JOptionPane.INFORMATION_MESSAGE); // Hiển thị thông báo nếu không tìm thấy khách hàng
	    }
	}


	private void jTextFieldSoDienThoaiActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFieldSoDienThoaiActionPerformed
	}// GEN-LAST:event_jTextFieldSoDienThoaiActionPerformed
// GEN-LAST:event_jTextFieldSoDienThoaiActionPerformed
	

	
	private void jTextFieldTenNhanVienActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFieldTenNhanVienActionPerformed
		// TODO add your handling code here:
	}
    // GEN-FIRST:event_jComboBoxThietBiActionPerformed
    // TODO add your handling code here:
    // GEN-LAST:event_jComboBoxThietBiActionPerformed
    // GEN-LAST:event_jTextFieldTenNhanVienActionPerformed

	private void jComboBoxDichVuActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jComboBoxDichVuActionPerformed
		 int i = jComboBoxDichVu.getSelectedIndex(); // Lấy chỉ mục đã chọn từ jComboBox
 	    ArrayList<DichVu> dsdv = dv_dao.getDsDichVu(); // Lấy danh sách dịch vụ từ dv_dao

 	    // Kiểm tra nếu chỉ mục hợp lệ
 	    if (i >= 0 && i < dsdv.size()) {
 	        // Lấy số lượng từ jSpinner
 	        int soLuong = (int) jSpinnerSoLuongDichVu.getValue();

 	        // Tính tiền dựa trên số lượng và giá dịch vụ
 	        double tien = soLuong * dsdv.get(i).getGiaDichVu();

 	        // Hiển thị tổng tiền trong jTextFieldGiaDichVu
 	        jTextFieldGiaDichVu.setText(String.valueOf(tien));
 	    }
 	    
	}// GEN-LAST:event_jComboBoxDichVuActionPerformed

	private void jTextFieldTongTienActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFieldTongTienActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextFieldTongTienActionPerformed

	private void jTextFieldTenKhachHangActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFieldTenKhachHangActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextFieldTenKhachHangActionPerformed
// GEN-LAST:event_jTextFieldTenKhachHangActionPerformed

	private void jTextFieldTienCocActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFieldTienCocActionPerformed
		// TODO add your handling code here:
	}
    // GEN-FIRST:event_jButtonThemThietBiActionPerformed
    // TODO add your handling code here:
    // GEN-LAST:event_jButtonThemThietBiActionPerformed
    // GEN-LAST:event_jTextFieldTienCocActionPerformed

	private void jButtonThemDichVuActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonThemDichVuActionPerformed
		int i = jComboBoxDichVu.getSelectedIndex(); // Lấy chỉ mục đã chọn từ jComboBox
 	    ArrayList<DichVu> dsdv = dv_dao.getDsDichVu(); // Lấy danh sách dịch vụ từ dv_dao
 	   if (i >= 0 && i < dsdv.size()) {
	        // Lấy số lượng từ jSpinner
	        int soLuong = (int) jSpinnerSoLuongDichVu.getValue();

	        // Tính tiền dựa trên số lượng và giá dịch vụ
	        double tien = soLuong * dsdv.get(i).getGiaDichVu();

	        // Hiển thị tổng tiền trong jTextFieldGiaDichVu
	        modelDichVu.addRow(new Object[] {
	        		dsdv.get(i).getMaDichVu(), dsdv.get(i).getTenDichVu(),soLuong,tien 
	        });
	        jTextFieldTongTien.setText( Double.toString(tinhTongTien()));
	    }
	}// GEN-LAST:event_jButtonThemDichVuActionPerformed
// GEN-LAST:event_jButtonThemDichVuActionPerformed

	private void jTextFieldGiaDichVuActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFieldGiaDichVuActionPerformed
		// TODO add your handling code here:
	}
    // GEN-FIRST:event_jTextFieldGiaThietBiActionPerformed
    // TODO add your handling code here:
    // GEN-LAST:event_jTextFieldGiaThietBiActionPerformed
    // GEN-LAST:event_jTextFieldGiaDichVuActionPerformed

	private void jButtonHuyActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonHuyActionPerformed
		if (parentFrame != null) {
            parentFrame.dispose(); // Đóng JFrame chứa JPanel này
        }	
	}// GEN-LAST:event_jButtonHuyActionPerformed
		
	private void jRadioButtonDatTruocActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jRadioButtonDatTruocActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jRadioButtonDatTruocActionPerformed
// GEN-LAST:event_jRadioButtonDatTruocActionPerformed

	private void jRadioButtonDatActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jRadioButtonDatActionPerformed
		// TODO add your handling code here:
	}
    // GEN-FIRST:event_jComboBoxVoucherActionPerformed
    // TODO add your handling code here:
    // GEN-LAST:event_jComboBoxVoucherActionPerformed
    // GEN-LAST:event_jRadioButtonDatActionPerformed

	private void jRadioButtonGioActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jRadioButtonGioActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jRadioButtonGioActionPerformed

	private void jRadioButtonNgayActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jRadioButtonNgayActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jRadioButtonNgayActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDatPhong;
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnThemDV;
    private javax.swing.JButton btnThemKH;
    private javax.swing.JButton btnXoaDV;
    private javax.swing.JButton btnXoaKH;
    private javax.swing.JButton btnXoaKHToanBo;
    private javax.swing.JButton btnXoaToanBoDV;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JComboBox<String> comBoBoxDV;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel labelGia;
    private javax.swing.JLabel labelLoaiPhong;
    private javax.swing.JLabel labelNhanVien;
    private javax.swing.JLabel labelPhong;
    private javax.swing.JRadioButton radioNguoiLon;
    private javax.swing.JRadioButton radioTreEm;
    private javax.swing.JSpinner spinnerSL;
    private javax.swing.JTable tableDV;
    private javax.swing.JTable tableKH;
    private javax.swing.JTable tablePhong;
    private javax.swing.JTextField txtCCCD;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTenKH;
    private javax.swing.JTextField txtTenKHCT;
    // End of variables declaration//GEN-END:variables
}
